const LOGIN_REQUEST = "@@app/LOGIN_REQUEST";
const LOGIN_IN_PROGRESS = "@@app/LOGIN_IN_PROGRESS";
const LOGIN_SUCCESS = "@@app/LOGIN_SUCCESS";
const LOGIN_FAILED = "@@app/LOGIN_FAILED";
const LOGOUT_REQUEST = "@@app/LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "@@app/LOGOUT_SUCCESS";

const FETCH_CURRENT_USER_PERMISSIONS_INIT =
  "@@app/FETCH_CURRENT_USER_PERMISSIONS_INIT";
const FETCH_CURRENT_USER_PERMISSIONS_IN_PROGRESS =
  "@@app/FETCH_CURRENT_USER_PERMISSIONS_IN_PROGRESS";
const FETCH_CURRENT_USER_PERMISSIONS_SUCCESS =
  "@@app/FETCH_CURRENT_USER_PERMISSIONS_SUCCESS";
const FETCH_CURRENT_USER_PERMISSIONS_FAILED =
  "@@app/FETCH_CURRENT_USER_PERMISSIONS_FAILED";

const FETCH_CURRENT_USER_MENUITEMS_INIT =
  "@@app/FETCH_CURRENT_USER_MENUITEMS_INIT";
const FETCH_CURRENT_USER_MENUITEMS_IN_PROGRESS =
  "@@app/FETCH_CURRENT_USER_MENUITEMS_IN_PROGRESS";
const FETCH_CURRENT_USER_MENUITEMS_SUCCESS =
  "@@app/FETCH_CURRENT_USER_MENUITEMS_SUCCESS";
const FETCH_CURRENT_USER_MENUITEMS_FAILED =
  "@@app/FETCH_CURRENT_USER_PERMISSIONS_FAILED";

export default {
  LOGIN_REQUEST,
  LOGIN_IN_PROGRESS,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  FETCH_CURRENT_USER_PERMISSIONS_INIT,
  FETCH_CURRENT_USER_PERMISSIONS_IN_PROGRESS,
  FETCH_CURRENT_USER_PERMISSIONS_SUCCESS,
  FETCH_CURRENT_USER_PERMISSIONS_FAILED,
  FETCH_CURRENT_USER_MENUITEMS_INIT,
  FETCH_CURRENT_USER_MENUITEMS_IN_PROGRESS,
  FETCH_CURRENT_USER_MENUITEMS_SUCCESS,
  FETCH_CURRENT_USER_MENUITEMS_FAILED
};
