const LIST_INIT = "@@data-list/INIT";
const LIST_INIT_IN_PROGRESS = "@@data-list/INIT_IN_PROGRESS";
const LIST_INIT_FAILED = "@@data-list/INIT_FAILED";
const LIST_INIT_SUCCESS = "@@data-list/INIT_SUCCESS";
const LIST_FETCH_DATA_REQUEST = "@@data-list/FETCH_DATA_REQUEST";
const LIST_FETCH_DATA_IN_PROGRESS = "@@data-list/FETCH_DATA_IN_PROGRESS";
const LIST_FETCH_DATA_SUCCESS = "@@data-list/FETCH_DATA_SUCCESS";
const LIST_FETCH_DATA_FAILED = "@@data-list/FETCH_DATA_FAILED";
const LIST_CHANGE_PAGE_NUMBER = "@@data-list/CHANGE_PAGE_NUMBER";
const LIST_CHANGE_SORT = "@@data-list/CHANGE_SORT";
const LIST_CHANGE_FILTER = "@@data-list/CHANGE_FILTER";
const LIST_CHANGE_ROWS_PER_PAGE = "@@data-list/CHANGE_ROWS_PER_PAGE";
const LIST_UPDATE_EDITED_ROWS = "@@data-list/UPDATE_EDITED_ROWS";
const LIST_SAVE_ROWS_INIT = "@@data-list/SAVE_ROWS_INIT";
const LIST_SAVE_ROWS_IN_PROGRESS = "@@data-list/SAVE_ROWS_IN_PROGRESS";
const LIST_SAVE_ROWS_SUCCESS = "@@data-list/SAVE_ROWS_SUCCESS";
const LIST_SAVE_ROWS_FAILED = "@@data-list/SAVE_ROWS_FAILED";
const LIST_DELETE_ROWS_INIT = "@@data-list/DELETE_ROWS_INIT";
const LIST_DELETE_ROWS_CANCELED = "@@data-list/DELETE_ROWS_CANCELED";
const LIST_DELETE_ROWS_CONFIRMED = "@@data-list/DELETE_ROWS_CONFIRMED";
const LIST_DELETE_ROWS_IN_PROGRESS = "@@data-list/DELETE_ROWS_IN_PROGRESS";
const LIST_DELETE_ROWS_SUCCESS = "@@data-list/DELETE_ROWS_SUCCESS";
const LIST_DELETE_ROWS_FAILED = "@@data-list/DELETE_ROWS_FAILED";
const LIST_CHECK_ROWS = "@@data-list/CHECK_ROWS";
const LIST_ADD_NEW_ROW = "@@data-list/ADD_NEW_ROW";
const LIST_CUSTOMIZE = "@@data-list/CUSTOMIZE";
const LIST_VALIDATE = "@@data-list/VALIDATE";

export default {
  LIST_INIT,
  LIST_INIT_IN_PROGRESS,
  LIST_INIT_FAILED,
  LIST_INIT_SUCCESS,
  LIST_FETCH_DATA_REQUEST,
  LIST_FETCH_DATA_IN_PROGRESS,
  LIST_FETCH_DATA_SUCCESS,
  LIST_FETCH_DATA_FAILED,
  LIST_CHANGE_PAGE_NUMBER,
  LIST_CHANGE_SORT,
  LIST_CHANGE_FILTER,
  LIST_CHANGE_ROWS_PER_PAGE,
  LIST_UPDATE_EDITED_ROWS,
  LIST_SAVE_ROWS_INIT,
  LIST_SAVE_ROWS_IN_PROGRESS,
  LIST_SAVE_ROWS_SUCCESS,
  LIST_SAVE_ROWS_FAILED,
  LIST_DELETE_ROWS_INIT,
  LIST_DELETE_ROWS_CANCELED,
  LIST_DELETE_ROWS_CONFIRMED,
  LIST_DELETE_ROWS_IN_PROGRESS,
  LIST_DELETE_ROWS_SUCCESS,
  LIST_DELETE_ROWS_FAILED,
  LIST_CHECK_ROWS,
  LIST_ADD_NEW_ROW,
  LIST_CUSTOMIZE,
  LIST_VALIDATE
};
