const PAGE_USERGROUPLIST_SHOW_EDITACCESS =
  "@@page-usergrouplist/SHOW_EDITACCESS";
const PAGE_USERGROUPLIST_HIDE_EDITACCESS =
  "@@page-usergrouplist/HIDE_EDITACCESS";

export default {
  PAGE_USERGROUPLIST_SHOW_EDITACCESS,
  PAGE_USERGROUPLIST_HIDE_EDITACCESS
};
