const DETAIL_INIT = "@@data-detail/INIT";
const DETAIL_INIT_IN_PROGRESS = "@@data-detail/INIT_IN_PROGRESS";
const DETAIL_INIT_FAILED = "@@data-detail/INIT_FAILED";
const DETAIL_INIT_SUCCESS = "@@data-detail/INIT_SUCCESS";
const DETAIL_FETCH_DATA_REQUEST = "@@data-detail/FETCH_DATA_REQUEST";
const DETAIL_FETCH_DATA_IN_PROGRESS = "@@data-detail/FETCH_DATA_IN_PROGRESS";
const DETAIL_FETCH_DATA_SUCCESS = "@@data-detail/FETCH_DATA_SUCCESS";
const DETAIL_FETCH_DATA_FAILED = "@@data-detail/FETCH_DATA_FAILED";
const DETAIL_UPDATE_EDITED_DATA = "@@data-detail/UPDATE_EDITED_DATA";
const DETAIL_SAVE_INIT = "@@data-detail/SAVE_INIT";
const DETAIL_SAVE_IN_PROGRESS = "@@data-detail/SAVE_IN_PROGRESS";
const DETAIL_SAVE_SUCCESS = "@@data-detail/SAVE_SUCCESS";
const DETAIL_SAVE_FAILED = "@@data-detail/SAVE_FAILED";
const DETAIL_DELETE_INIT = "@@data-detail/DELETE_INIT";
const DETAIL_DELETE_CANCELED = "@@data-detail/DELETE_CANCELED";
const DETAIL_DELETE_CONFIRMED = "@@data-detail/DELETE_CONFIRMED";
const DETAIL_DELETE_IN_PROGRESS = "@@data-detail/DELETE_IN_PROGRESS";
const DETAIL_DELETE_SUCCESS = "@@data-detail/DELETE_SUCCESS";
const DETAIL_DELETE_FAILED = "@@data-detail/DELETE_FAILED";
const DETAIL_ADD_NEW = "@@data-detail/ADD_NEW";
const DETAIL_CUSTOMIZE = "@@data-detail/CUSTOMIZE";
const DETAIL_VALIDATE = "@@data-detail/VALIDATE";
const DETAIL_UPDATE_REDIRECT_URL = "@@data-detail/DETAIL_UPDATE_REDIRECT_URL";

export default {
  DETAIL_INIT,
  DETAIL_INIT_IN_PROGRESS,
  DETAIL_INIT_FAILED,
  DETAIL_INIT_SUCCESS,
  DETAIL_FETCH_DATA_REQUEST,
  DETAIL_FETCH_DATA_IN_PROGRESS,
  DETAIL_FETCH_DATA_SUCCESS,
  DETAIL_FETCH_DATA_FAILED,
  DETAIL_UPDATE_EDITED_DATA,
  DETAIL_SAVE_INIT,
  DETAIL_SAVE_IN_PROGRESS,
  DETAIL_SAVE_SUCCESS,
  DETAIL_SAVE_FAILED,
  DETAIL_DELETE_INIT,
  DETAIL_DELETE_CANCELED,
  DETAIL_DELETE_CONFIRMED,
  DETAIL_DELETE_IN_PROGRESS,
  DETAIL_DELETE_SUCCESS,
  DETAIL_DELETE_FAILED,
  DETAIL_ADD_NEW,
  DETAIL_CUSTOMIZE,
  DETAIL_VALIDATE,
  DETAIL_UPDATE_REDIRECT_URL
};
