const PAGE_USERLIST_SHOW_EDITACCESS = "@@page-userlist/SHOW_EDITACCESS";
const PAGE_USERLIST_HIDE_EDITACCESS = "@@page-userlist/HIDE_EDITACCESS";

export default {
  PAGE_USERLIST_SHOW_EDITACCESS,
  PAGE_USERLIST_HIDE_EDITACCESS
};
